test_questions = [
    "How much was spent on public safety by the Town of Cary in 2010?",
    "How many programs were done under the class of General Government in the expenditure of the Town of Cary?",
    "How much did the Town of Cary earn in 2010?",
    "Which class achieved the highest revenue for the Town of Cary?",
    "For which account type of whiteacre was spent the most?",
    "How much interest did the debt service of the city of Whiteacre spend?",
    "Which expenses had the highest total amount of proposed expenditures for the Maldives?",
    "What was the highest single expenditure amount proposed by the Maldives Broadcasting Corporation?",
    "Which Ugandan output had the highest budget in 2014?",
    "What was the average Uganda health budget amount in Namutumba District?",
    "How many suppliers did the Newcastle city council use for education?",
    "How many directorates does the Newcastle city council have?",
    "Which suppliers did the Waltham Forest Council utilize for recycling?",
    "On the Waltham Forest Council, how much money was given to the Forest Recycling Project?",
    "How many narratives are there for Cheshire West and Chester council spending in the category of Marketing?",
    "What are the top 3 expenditure categories in Cheshire West and Chester council spending?",
    "Which priorities does the insurance fund have for the City of Redacre?",
    "How many divisions have safety priority in the City of Redacre spending?",
    "What was the total Wandsworth spending in 2013 from the housing department?",
    "How much money does Wandsworth spendt on general internal repairs?",
    "Top 3 IW Council Spending service areas?",
    "Under which directorate does the IW Council service area have the highest revenue?",
    "Which departments of the city of Springfield had a higher budget in 2004 then in 2005?",
    "What is the highest single budget amount in the city of Springfield for public safety?",
    "Which of the Californian cities received the highest amount of money?",
    "Under which caption did Livermore receive the highest amount of money in 2011?",
    "What is the average Washington DC teacher salary?",
    "Which position has the highest average salary in Washington DC?",
    "How many big lottery found grants were given in the South West in 2012?",
    "Has there been a big lottery fund grant to Stanbury Court Social Club?",
    "On which expenses in Gloucestershire was spent more than 10000000 pound in total?",
    "How much money did Cheltenham Borough Homes receive?",
    "How much did the department for work and pensions pay for Research into Infrastructure?",
    "What are the geographic regions in the UK Country Regional Analysis from the scottish executive and its departments for forests?",
    "How much cost the implementation of Midwifery Education in Nangarhar?",
    "How much was spent on food security by Cordaid in Afghanistan?",
    "What was the total expenditure on Materials and Supplies of the City of Toronto in 2010?",
    "How much did Ireland charities pay  in total governance costs?",
    "What was the frontex staff budget in 2005?",
    "What was the smallest amount for industrial and commercial facilities in the Dublin City Council Expenditure Budget of 2013?",
    "Which country received the highest financial crisis aid?",
    "How much was charity spending was expended for charitable activities in Haiti?",
    "What is the amount given by the Metropolitan Police Department to Cybernational?",
    "What was the highest amount under the sub-account for layout and construction of buildingsin Cameroon in 2009?",
    "When did Canada get Nominet Trust funding for the last time?",
    "Which admin was reponsible for the most total running expenses in Armenia in 2009?",
    "How much is the total amount of statuatory transfers in Nigerias proposed budget of 2013?",
    "How much did the New York City Council Members give in 2015 for the Manhattan youth?",
    "What was the amount of the smallest community grant in the Fingal County Council expenditure budget?",
    "When was the upgrade of the Parks-Baba Park paid?"
];

training_questions = [
    "How much was spent on public works and utilities by the Town of Cary in 2011?",
    "Which programs were done under the class of public works and utilities in the expenditure of the Town of Cary?",
    "How much did the Town of Cary earn in 2009?",
    "Which program earned the most for the Town of Cary?",
    "Which department of whiteacre spent the most in 2010?",
    "How much does the general district court of Whiteacre spend for court appointed attorney fees a year?",
    "Which agencies in the Maldives have proposed expenditure amounts of more than 1 billion Maldivian rufiyaa in 2015?",
    "What is the total aid to the Anti Corruption Commission in the Maldives in 2015?",
    "Which Ugandan district had the highest budget in 2014?",
    "What was the average Uganda health budget over all districts in 2014?",
    "What is the highest Newcastle city council payment for supplies and services?",
    "What's are the 10 highest payments of the Newcastle city council?",
    "How much did the Waltham Forest Council spend on Environment and Regeneration?",
    "On the Waltham Forest Council, how much money was given to Synarbor Global Solutions Ltd?",
    "How much money give Cheshire West and Chester on Adult Social Care and Health?",
    "What are the top 5 narratives in Cheshire West and Chester?",
    "How much did the City of Redacre expend from the insurance fund?",
    "How much receives each division in the City of Redacre?",
    "What is the total Wandsworth spending from all departments?",
    "How much money Wandsworth spends on the criminal records bureau?",
    "Top 10 IW Council Spending expense types?",
    "Which IW Council service area has the highest spending?",
    "Which departments of the city of Springfield had a higher budget in 2005 then in 2006?",
    "What is the highest single budget amount in the city of Springfield for public works?",
    "Which proportion went to Fullerton of the amount spent on Californian cities in 2010?",
    "How many categories are there for californian cities?",
    "What was the highest Washington DC employee salary in 2011?",
    "What is the average salary of an Engineering Technician in Washington DC?",
    "What was the amount recieved by King George's Field from Big Lottery Fund grants?",
    "Over which programmes more than 1000000 pound but less than 10000000 pound in grants were given by the Big Lottery Fund?",
    "On which service areas of Gloucestershire was spent more than 1000000 pound in total?",
    "How much money did the Gloucestershire Police Authority receive?",
    "How much did the department for education pay for extra education services in Scotland?",
    "What HTM functions are paid from the department for education the UK?",
    "What are the activity statuses of basic health care in Urozgan?",
    "What is the total amount of basic nutrition aid by Cordaid in Afghanistan?",
    "What was the total budget on Technical Services in City of Toronto in 2009?",
    "Which divisions of the City of Toronto received more than 10000000 canadian dollar in 2010?",
    "How much did the Sightsavers charity in Ireland pay in total?",
    "How much money does the Special Olympics Ireland charity spend on generating funds?",
    "What is the frontex budget for administrative expenditure?",
    "What is the average frontex budget chapter budget?",
    "What was the largest amount spent on housing and building in the Dublin City Council Expenditure Budget of 2013?",
    "How much was the budget amount of the Dublin City Council in 2013?",
    "How much financial crisis aid did Austria receive in Guaranetees?",
    "How much financial crisis aid did Belgium receive in the year of 2011?",
    "How much was charity spending was expended for charitable activities in Bangladesh?",
    "What is the total cost of generating funds for public appeals events?",
    "What is the amount given by the Department of Health to VWR International LLC?",
    "How much was given in total to the Riverside Publishing vendor for educational purposes.",
    "What was the highest amount for materials and supplies used in Cameroon in 2008?",
    "How much is the total expenditure of the Tigerne Council in Cameroon?",
    "When did London get Nominet Trust funding?",
    "When did the Web in Society programme get Nominet Trust funding?",
    "How much did Armenia spent in 2009 on general public services?",
    "What are the budgetary classifications of running expenses in Armenia?",
    "In Nigerias proposed budget of 2013, how much is assigned to total overhead costs?",
    "How much did Nigernian Ministry of Petroleum Resources receive from ministries and department agencies?",
    "How much did the New York City Council Members give to the Gun Hill Basketball Association?",
    "In how many years did Dickens give money to American Performing Arts Collaborative, Inc.?",
    "How high were the service support costs of the Fingal County Council Expenditure Budget of 2011?",
    "What was the lowest amount for the veterinary service in the Fingal County Council expenditure budget?",
    "What is the total investment budget for basic education in Mezam, Cameroon?",
    "Which areas in Cameroon had an investment budget of more than 5 billion CFA in 2010?",
    "How much money was given to works and transport in the Ugandan budget?",
    "In which years did the Uganda budget contain money for Education?",
    "How many donor entities provided foreign aid for Typhoon Yolanda?",
    "How much foreign aid went over the Red Cross from China?",
    "Which type of sector is receiving the most Finland foreign aid in India?",
    "What types of foreign aid from Finland did Belarus receive in 2011?",
    "What was the proposed City of Providence budget amount for City Courts by the Muncipal Court?",
    "How much was the City of Providence budget for educational materials?",
    "When was upgrading and greening in ward 49 paid?",
    "What are the funding sources for Cape Town Electricity?",
    "Which investor type using CKAN technology received the most funding?",
    "When did Pew Charitable Trust invest?",
    "How much did Armenia spend in 2006 for buildings and edifices?",
    "Which were the admins for personal and catering materials in Armenia in 2006?",
    "How much was spent on public utilities in Armenia in 2007?",
    "What was the total cost of running expenses for Armenia in 2007?",
    "What was the total Scottish Government expenditure of 2013-01-09?",
    "What was the smallest amount expended for Environment and Forestry by the Scottish Government in January of 2013?",
    "In which year did the City of Oakland have the highest total expenditure budget?",
    "What was the total City of Oakland budget for the Administrative Unit in 2012?",
    "How high was the recurrent expenditure for the Sierra Leona Government budget in 2013?",
    "How much was budgeted for general services for the Office of the President of Sierra Leona in 2013?",
    "Which clients received lobbying contributions of more than 50000000 $?",
    "Which industry received the most lobbying contributions?",
    "How much did the Manchester City Council give for  Learning Disabilities to SLC Paragon?",
    "Which service areas do the Manchester City Council spendings contain?",
    "How much was Albanias 2013 budget for education?",
    "What are the identification numbers of housing and community amenities in Albanias 2013 budget?",
    "What was the total Kenya County Expenditure in Kiambu by the Thika administration?",
    "Which Kenya country administration had the highest expenditure budget?",
    "What was the Albania budget for public order and safety in 2007?",
    "What was the combined Albania budget for health from 2007 to 2010?",
    "What is the external debt amount of Kwara?",
    "How much external debt did rivers have in 2010?",
    "How many admins were responsible for mandatory payments in the Armenian approved budget of 2010?",
    "How much total running expenses under budgetary classification did the Armenian approved budget of 2010 have for personnel?"
];